version: '3'

services:
    reverse-proxy:
        networks:
            - ring
        hostname: pinqubator.com
        ports:
            - 80:80
            - 443:443
        build: ./reverse-proxy
        volumes:
            - ./reverse-proxy/html:/usr/share/nginx/html
            - ./reverse-proxy/conf/includes:/etc/nginx/includes
        depends_on:
            - backend
    broker:
        hostname: broker.pinqubator.com
        networks:
            - backend-network
        ports:
            - 5671:5671
        build:
            context: ./broker
    instants-db:
        hostname: instants-db.pinqubator.com
        ports:
            - 27017:27017
        build:
            context: ./instants-db
            args:
                database: test
                username: root
                password: qweasd
        volumes:
            - instants-volume:/data/db
        networks:
            - backend-network
    backend:
        hostname: backend.pinqubator.com
        ports:
            - 8443:8443
        networks:
            - ring
            - backend-network
        build:
            context: ./backend
            args:
                dbhost: instants-db.pinqubator.com
                dbport: 27017
        depends_on:
            - instants-db
            - broker

networks:
    ring:
    backend-network:

volumes:
    instants-volume: