version: '3'

services:
    reverse-proxy:
        networks:
            - ring
        hostname: pinqubator.com
        ports:
            - 80:80
            - 443:443
        build: ./reverse-proxy
        depends_on:
            - backend
            - frontend
    broker:
        hostname: broker.pinqubator.com
        ports:
            - 5671:5671
        networks:
            - backend-network
        build:
            context: ./broker
    instants-db:
        hostname: instants-db.pinqubator.com
        ports:
            - 27017:27017
        build:
            context: ./instants-db
            args:
                database: instants-db
                username: root
                password: qweasd
        volumes:
            - instants-volume:/data/db
        networks:
            - backend-network
    backend:
        hostname: backend.pinqubator.com
        networks:
            - ring
            - backend-network
        build:
            context: ./backend
            args:
                brokerhost: broker.pinqubator.com
                brokerport: 5671
                dbhost: instants-db.pinqubator.com
                dbport: 27017
                node_env: pro
        depends_on:
            - instants-db
            - broker
    frontend:
        hostname: frontend.pinqubator.com
        networks:
            - ring
        build:
            context: ./frontend
            args:
                https_port: 443
        depends_on:
            - backend

networks:
    ring:
    backend-network:

volumes:
    instants-volume: